### ISSUE TITLE
defnet needs a release to fix client bug

### ISSUE THREAD

**Issue by magroader** [britzl/defnet#5]
Defnet master currently differs from the latest release 5.0.1:
https://github.com/britzl/defnet/compare/5.0.1...master?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

master has a major bugfix in it that allows servers to send messages to clients - without it, you can't get the client object out and so can only broadcast to all clients.

Defnet should have a new release to get this bugfix into a tagged version.

**Comment by britzl** [comment]
Thanks for pointing this out! I've made a new release (5.0.2)
